fix: DBTP-1749 - Fix deploy status is null error (#329)
Co-authored-by: Will Gibson <8738245+WillGibson@users.noreply.github.com>

diff --git a/codebase-pipelines/buildspec-deploy.yml b/codebase-pipelines/buildspec-deploy.yml
--- a/codebase-pipelines/buildspec-deploy.yml
+++ b/codebase-pipelines/buildspec-deploy.yml
@@ -9,56 +9,13 @@ env:
 phases:
   install:
     commands:
-      - echo "Starting deployment script for ${SERVICE} service"
-      - pip install yq --quiet
-      - echo "Installing platform-helper"
-      - pip install dbt-platform-helper --quiet
-      - platform-helper --version
-      - echo "Installing regclient"
+      - pip install yq dbt-platform-helper --quiet
       - curl -s -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 > /usr/local/bin/regctl
       - chmod +x /usr/local/bin/regctl
 
   build:
     commands:
       - set -e
-
-      # Extract timestamp from image config and check if it exists
-      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
-
-      # construct Slack message env vars
-      - SLACK_REF=$(regctl image config "${REPOSITORY_URL}:${IMAGE_TAG}" | jq -r '.config.Labels."uk.gov.trade.digital.build.timestamp"')
-      - |
-        if [ "${SLACK_REF}" = "null" ] || [ -z "${SLACK_REF}" ]; then
-          echo "Image contains no timestamp label"
-          exit 1
-        fi
-        echo "Found image timestamp ${SLACK_REF}"
-
-      - UPPERCASE_SERVICE=$(echo "${SERVICE}" | tr '[:lower:]' '[:upper:]')
-      - UPPERCASE_TAG=$(echo "${IMAGE_TAG}" | tr '[:lower:]' '[:upper:]')
-
-        # Extract the pipeline name from CODEBUILD_INITIATOR default env var
-      - |
-        if [[ "${CODEBUILD_INITIATOR}" == codepipeline/* ]]; then 
-          PIPELINE_NAME=$(echo "${CODEBUILD_INITIATOR}" | cut -d'/' -f2) 
-          echo "Pipeline name is ${PIPELINE_NAME}"
-        else 
-          echo "ERROR: Build not triggered by CodePipeline." 
-          exit 1 
-        fi
-
-      # Construct the pipeline execution URL
-      - PIPELINE_EXECUTION_URL="https://${AWS_REGION}.console.aws.amazon.com/codesuite/codepipeline/pipelines/${PIPELINE_NAME}/executions/${PIPELINE_EXECUTION_ID}" 
-
-      - echo "Pipeline execution URL ${PIPELINE_EXECUTION_URL}"
-
-      - BUILD_ID_PREFIX=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)
-      - echo "BUILD_ID_PREFIX - ${BUILD_ID_PREFIX}"
-
-      - |
-        MESSAGE=":rocket: STARTED - Deployment of ${UPPERCASE_SERVICE} service - Tag: ${UPPERCASE_TAG} - <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution url>"
-
-      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
 
       # Check if the specified image tag exists
       - |
@@ -74,6 +31,39 @@ phases:
           exit 1
         fi
 
+      # Extract timestamp from image config and check if it exists
+      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+
+      # Construct Slack message env vars
+      - SLACK_REF=$(regctl image config "${REPOSITORY_URL}:${IMAGE_TAG}" | jq -r '.config.Labels."uk.gov.trade.digital.build.timestamp"')
+      - |
+        if [ "${SLACK_REF}" = "null" ] || [ -z "${SLACK_REF}" ]; then
+          echo "Error: Image contains no timestamp label"
+          exit 1
+        fi
+
+      - UPPERCASE_SERVICE=$(echo "${SERVICE}" | tr '[:lower:]' '[:upper:]')
+      - UPPERCASE_TAG=$(echo "${IMAGE_TAG}" | tr '[:lower:]' '[:upper:]')
+
+      # Extract the pipeline name from CODEBUILD_INITIATOR default env var
+      - |
+        if [[ "${CODEBUILD_INITIATOR}" == codepipeline/* ]]; then 
+          PIPELINE_NAME=$(echo "${CODEBUILD_INITIATOR}" | cut -d'/' -f2) 
+        else 
+          echo "Error: Build not triggered by CodePipeline." 
+          exit 1 
+        fi
+
+      # Construct the pipeline execution URL
+      - PIPELINE_EXECUTION_URL="https://${AWS_REGION}.console.aws.amazon.com/codesuite/codepipeline/pipelines/${PIPELINE_NAME}/executions/${PIPELINE_EXECUTION_ID}"
+      - BUILD_ID_PREFIX=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)
+
+      - |
+        MESSAGE=":rocket: STARTED - Deployment of ${UPPERCASE_SERVICE} service - Tag: ${UPPERCASE_TAG} - <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution url>"
+
+      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
+
+      # Build image uri
       - task_family="${APPLICATION}-${ENVIRONMENT}-${SERVICE}"
       - cluster="${APPLICATION}-${ENVIRONMENT}"
       - image_uri="${REPOSITORY_URL}:${IMAGE_TAG}"
@@ -127,13 +117,15 @@ phases:
 
       # Check deployment status
       - |
-        while [[ "${deploy_status}" == "IN_PROGRESS" || "${deploy_status}" == "PENDING" || "${deploy_status}" == "ROLLBACK_IN_PROGRESS" ]];
+        while [[ "${deploy_status}" == "IN_PROGRESS" || "${deploy_status}" == "PENDING" || "${deploy_status}" == "ROLLBACK_IN_PROGRESS" || "${deploy_status}" == "null" ]];
         do
           sleep 10
           now=$( date +%s )
           elapsed=$(( now-start ))
 
           deploy_status=$(aws ecs list-service-deployments --cluster "${cluster}" --service "${service_name}" --created-at "after=${start}" | jq -r '.serviceDeployments[0].status')
+        
+          if [[ "${deploy_status}" == "null" ]]; then deploy_status="PENDING"; fi
           echo "Deployment status after ${elapsed} seconds: ${deploy_status}"
 
           if [[ ${elapsed} -gt ${DEPLOY_TIMEOUT} ]]; then
@@ -162,11 +154,8 @@ phases:
             STATUS_TEXT="STOP_REQUESTED/STOPPED/PENDING/IN_PROGRESS"
             ;;
         esac
-        
-      - echo "Status emoji set to ${STATUS_EMOJI}"
 
       - MESSAGE="${STATUS_EMOJI} ${STATUS_TEXT} - Deployment of ${UPPERCASE_TAG} to ${UPPERCASE_SERVICE} service - ${deploy_status} - <${PIPELINE_EXECUTION_URL}|Pipeline execution url>"
-
       - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
 
       # Exit with an error code if deployment did not succeed
@@ -174,4 +163,14 @@ phases:
         if [ "${deploy_status}" != "SUCCESSFUL" ]; then
           echo "Error: deployment status is ${deploy_status}"
           exit 1
+        fi
+
+  post_build:
+    commands:
+      - |
+        if [ "${CODEBUILD_BUILD_SUCCEEDING}" != "1" ]; then
+          BUILD_ID_PREFIX=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)          
+          MESSAGE=":red_circle::warning: ERROR - Deployment of ${UPPERCASE_TAG} to ${UPPERCASE_SERVICE} service - FAILED <https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=eu-west-2|Build log>"
+          
+          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
         fi
