Re-add copilot install and commands for non-prod environments

diff --git a/environment-pipelines/buildspec-install-build-tools.yml b/environment-pipelines/buildspec-install-build-tools.yml
--- a/environment-pipelines/buildspec-install-build-tools.yml
+++ b/environment-pipelines/buildspec-install-build-tools.yml
@@ -13,6 +13,12 @@ phases:
     commands:
       - set -e
       - echo "Deploying ${APPLICATION} environments"
+      - |
+          if [ ! -f .copilot-version ]; then
+            echo "Cannot find .copilot-version file"
+            exit 1
+          fi
+      - COPILOT_VERSION=`cat .copilot-version`
       - cd "${CODEBUILD_SRC_DIR}"
       - echo "Installing latest version of platform-helper to get required version for the project."
       - pip install dbt-platform-helper
@@ -66,6 +72,8 @@ phases:
       - unzip terraform_install.zip
       - chmod +x terraform
       - rm terraform_install.zip
+      - curl -s -qL -o copilot https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v${COPILOT_VERSION}
+      - chmod +x copilot
       - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Starting install phase"
       - VERSION_OUTPUT+="\n$(terraform --version)"
       - VERSION_OUTPUT+="\n$(platform-helper --version)"
