Changes to buildspec to support  changing the version of platform-helper installed

diff --git a/environment-pipelines/buildspec-install-build-tools.yml b/environment-pipelines/buildspec-install-build-tools.yml
--- a/environment-pipelines/buildspec-install-build-tools.yml
+++ b/environment-pipelines/buildspec-install-build-tools.yml
@@ -13,17 +13,47 @@ phases:
     commands:
       - set -e
       - echo "Deploying ${APPLICATION} environments"
+      - cd "${CODEBUILD_SRC_DIR}"
+      - echo -e "\nGet CodeStar connection details"
+      - codestar_connections=$(aws codestar-connections list-connections --provider-type GitHub --query "Connections[? ConnectionStatus == 'AVAILABLE']")
+      - aws_account=$(echo "$codestar_connections" | jq -r ".[0].OwnerAccountId")
+      - codestar_arn=$(echo "$codestar_connections" | jq -r ".[0].ConnectionArn")
+      - codestar_connection_id=$(echo "${codestar_arn##*/}")
+      - export GIT_CLONE_BASE_URL="https://codestar-connections.eu-west-2.amazonaws.com/git-http/$aws_account/eu-west-2/$codestar_connection_id/uktrade"
+      - git config --global credential.helper '!aws codecommit credential-helper $@'
+      - git config --global credential.UseHttpPath true
+      - git clone -b DBTP-1153-main-branch-tools "${GIT_CLONE_BASE_URL}/platform-tools.git"
+      - export PYTHONPATH=$PYTHONPATH:platform-tools
+      - yum -y install python-pip
+      - pip install click requests jinja2 pyyaml boto3 schema
+      - REQUIRED_VERSION=$(python -c "from dbt_platform_helper.utils.versioning import get_desired_platform_helper_version; print(get_desired_platform_helper_version(pipeline='${PIPELINE_NAME}'))")
+      - COMMIT_TYPE=$(python -c "import re, sys; print('tag' if re.match(r'\\d+\\.\\d+\\.\\d+', '${REQUIRED_VERSION}') else 'commit')")
+      - echo "Required Version - ${REQUIRED_VERSION}; Type - ${COMMIT_TYPE}"
+      - echo "Installing build tools"
+      - mkdir ./build-tools
+      - |
+          if [ "${COMMIT_TYPE}" == "tag" ]
+          then
+            echo "Installing platform-helper from release ${REQUIRED_VERSION}"
+            cd ./build-tools
+            pip install --target . --quiet dbt-platform-helper==${REQUIRED_VERSION}
+          else
+            pip install poetry
+            echo "Installing platform-helper from branch/commit ${REQUIRED_VERSION}"
+            cd platform-tools
+            git checkout "${REQUIRED_VERSION}"
+            poetry build --no-interaction --format sdist --no-ansi
+            cd "${CODEBUILD_SRC_DIR}/build-tools"
+            pip install --target . --quiet "../platform-tools/dist/$(ls -t1 dist | head -1)"
+          fi
+      - platform-helper --version
+      - exit 1
       - VERSION_OUTPUT=""
       - |
         if [ ! -f .platform-helper-version ]; then
           echo "Cannot find .platform-helper-version file"
           exit 1
         fi
-      - PLATFORM_HELPER_VERSION=`cat .platform-helper-version`
-      - echo "Installing build tools"
-      - yum -y install python-pip
-      - mkdir ./build-tools
-      - cd ./build-tools
       - pip install --target . --quiet dbt-platform-helper==$PLATFORM_HELPER_VERSION
       - export "PATH=$(pwd)/bin:$PATH"
       - export PYTHONPATH=$(pwd)
